### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by Laurentsos** [5cover/WinClean#1]
Hello, do you plan to make a portable version?

**Comment by 5cover** [comment]
I don't think this is possible without removing some features but I will see for next release.

**Comment by Laurentsos** [comment]
Thanks

**Comment by Laurentsos** [comment]
For the portable version, it would be nice if it could save in the Winclean directory rather than in %appdata%

**Comment by 5cover** [comment]
> For the portable version, it would be nice if it could save in the Winclean directory rather than in %appdata%

I'm not sure what you mean, but since the portable version is shipped as a standalone executable, saving stuff in the WinClean directory could pollute its containing directory.
