### ISSUE TITLE
Incorrect Wiki Link in README.md

### ISSUE THREAD

**Issue by ben-blake** [5cover/WinClean#11]
### The README.md file contains a hyperlink with an incorrect URL for the wiki section.

**The issue is specifically with the line:**
https://github.com/5cover/WinClean/blob/4823a81acaf4e8416bb6d32ff898951783ccabfb/README.md?plain=1#L20

**The correct link should be:**
`https://github.com/5cover/WinClean/wiki`
> The only difference is the lowercase "w" in "wiki." The current link with the uppercase "W" results in a broken link.

**Steps to Reproduce:**

> Visit the README.md file at [README.md](https://github.com/5cover/WinClean/blob/main/README.md).
> Locate the line "More information and tutorials on the [wiki](https://github.com/5cover/WinClean/Wiki/)."

**Expected Behavior:**
> The hyperlink should lead to the correct wiki URL: "https://github.com/5cover/WinClean/wiki/."

**Comment by 5cover** [comment]
Thanks!
