### ISSUE TITLE
[SCHi!  Everytime (recent) that I have tried to run Winclean (amazing App) I get a message that .Net Desktop Runtime  needs installing.   RIPT]

### ISSUE THREAD

**Issue by ModaKevin** [5cover/WinClean#5]
*Hi!  Everytime (recent) that I have tried to run Winclean (amazing App) I get a message that .Net Desktop Runtime  needs installing.   The screen shot is attached.   I 
![Error Mess Winclean gene](https://user-images.githubusercontent.com/77555382/221435567-f7e97c20-6bfd-4a1c-bbe2-0a3b6b57516f.png)
even have the new 7 version of .net.   
![Error Mess Winclean gene](https://user-images.githubusercontent.com/77555382/221435802-093053b6-e97a-4e72-85c3-468b5407fd37.png)

**Comment by Matto58** [comment]
> even have the new 7 version of .net.

the popup states you need .net 6.0, not .net 7.0

**Comment by 5cover** [comment]
Try to reinstall WinClean. The installer will automatically download the appropriate .NET version.
